title: <p align="center"> The Cocktail Fork Problem</br>Three-Stem Audio Separation for Real-World Soundtracks </p>
description: Resources page for the Divide and Remaster (DnR) dataset introduced as part of the CFP paper
theme: jekyll-theme-tactile

