title: The Cocktail Fork Problem - Three-Stem Audio Separation for Real-World Soundtracks
description: Resources page for the Divide and Remaster (DnR) dataset introduced as part of the CFP paper
theme: jekyll-theme-tactile

